"""create note table

Revision ID: 207f42539798
Revises: 6ac9820fadb9
Create Date: 2026-07-02 17:07:55.246236

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "207f42539798"
down_revision: str | None = "6ac9820fadb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "color",
            sa.Enum("GOLD", "AVOCAT", "SALSA", "CLAY", "TEAL", name="notecolor"),
            nullable=False,
        ),
        sa.Column("visibility", sa.Enum("PRIVATE", "PUBLIC", name="visibility"), nullable=False),
        sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_note_owner_id"), ["owner_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_note_owner_id"))

    op.drop_table("note")
    # ### end Alembic commands ###

    # Postgres: drop_table leaves the native ENUM types behind — drop them explicitly.
    # No-op on SQLite (enums are plain VARCHAR there).
    sa.Enum(name="notecolor").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="visibility").drop(op.get_bind(), checkfirst=True)
